name: Build and Deploy

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Change to frontend directory
        run: cd frontend

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build the project
        run: npm run build:prod
        working-directory: ./frontend

      - name: Upload artifacts for deployment
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            ./frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts from build
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ./build

      - name: Clean remote directory
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            mv /public_html/.htaccess /backup/ || { echo "Fehler beim Verschieben der .htaccess"; exit 1; }
            rm -rf /public_html/* || { echo "Fehler beim Löschen des Inhalts von /public_html/"; exit 1; }
            mv /backup/.htaccess /public_html/ || { echo "Fehler beim Zurückverschieben der .htaccess"; exit 1; }


      - name: Upload files via SFTP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          source: "./build/*"
          target: "/public_html"
